services:

  mystock-demo:
    build: .
    container_name: mystock-demo
    env_file:
      - .env
    volumes:
      - mystock_data:/app/backend/data
    networks:
      - portfolio-net
    restart: unless-stopped

volumes:
  mystock_data:

networks:
  portfolio-net:
    external: true
